### PR TITLE
Switch package references to npm

### PR DESCRIPTION
**Pull request by jdub233**
Switches to npmjs references for open source packages, to make them easier to work with.

Leaves burf-customizations as a private package from github packages.

### CODE REVIEW

**Review by ashleykolodziej — APPROVED** [review]

**Review by desrosj — APPROVED** [review]

**Comment by ashleykolodziej** [comment]
Alright @jdub233 - @desrosj has sneakily shown me I think I'm the holdup here. I completely forgot what's next to keep this moving, and I feel like you told me and I don't know what it was. Do we just... merge and see what happens? Does this action publish to npm?

**Comment by jdub233** [comment]
This just updates the references, it doesn't include a Github action.

We probably should setup an action, but I can also publish it manually to get things started.

**Comment by ashleykolodziej** [comment]
@jdub233 I think if you can publish it initially, I could probably edit this action to publish to the right place. It might already even work if we get a secret in the repo - I think that's the part I'm missing.

**Comment by jdub233** [comment]
These have all been published to npmjs and should now be installable from there:
https://www.npmjs.com/search?q=%40bostonuniversity%2Fburf

I did the first publish by hand, but if they look good there then updating the GitHub action to auto publish them should be straightforward.

**Review by ashleykolodziej — APPROVED** [review]

**Pull request merged**
