### PR TITLE
Feature/es6 support

### PR DESCRIPTION
**Pull request by toddmilliken**
This pull-request addresses a concern brought up in a Framework 2x issue https://github.com/bu-ist/responsive-framework/issues/74 . But more importantly, it refactors how we plan to maintain JavaScript in our projects moving forward.

The goal of this PR is to jump into the bleeding-edge of javascript development so no dev gets left behind 😄 . We will now be able to write all the es6 we want and have it transpile down to es5 JS that all browsers can understand. Each commit has been outlined as a step in this process.

Here is a quick run-down:

1. Adds `grunt-browserify` so we can separate files into modules. Browserify lets you require('modules') in the browser by bundling up all of your dependencies. This means we won't have to manually run a concatenation script to join files together into one file. It's worth noting that this package alone isn't enough for the es6 goodness -- it just allows us to use `require` in our files and provides a way for browsers to understand that Node style/CommonJS module style of requiring smaller files into a larger file. Which brings me to point number 2.
2. Adds a `babelify` transform for the Browserify task. This package (in addition to `@babel/core` and `@babel/preset-env`) will allow us to use `import` and `export` as well as all the es6 features needed to support our browsers, which brings me to point number 3.
3. Adds a `browserslist` key in package.json to define what browsers we support. Front-end tooling such as babel and autoprefixer can read from this entry and polyfill features/add vendor prefixes based on the criteria. More info here https://github.com/browserslist/browserslist .
4. Adds a `.babelrc` file for configuring babel. This is common in any babel project in a monolithic repo setup (single project repo) and a recommended way of configuring babel with the presets you intend to use (we're currently just using the popular `@babel/preset-env` preset but we could add WP presets for react and whatnot.
5. Refactors the JS so that its following the new procedure of having a root js entry point (`main.js`) and importing whatever modules we need.

Notes:
- Browserify: gives ability to use node style `require` in the browser. Huge for dependency management
- Babelify: a transform we can pass to Browserify. Gives ability for us to write es6 style modules using `imports/exports`. This package takes those import/export lines and transpiles them to `require` which Browserify can understand and send to the browser. It also gives us the ability to write in es6 and take advantage of latest JS features.
- You can add as many root files in `js-dev/*.js` as you want; they will all get their own compiled version in `js/*.js` along with a minified version and a sourcemap. The names are consistent with whatever the file was named with in the `js-dev/` folder.
- For smaller files we want to import, its best to follow the practice of stashing them in a modules or components subdirectory in js-dev. For example `js-dev/modules/toggle.js` is where that specific code lives; that file then gets imported from the `main.js` file via the `import ./modules/toggle` line.

### CODE REVIEW

**Comment by toddmilliken** [comment]
@anton-kachurin - revised so the unminified version is overwritten by the uglified (minified) version. This resolves your inquiry that the unminified version was too hard to read and should be removed, and we should just use the minified version only with a source map.

@stonybrookweb - renamed `main.js` to be `theme.js` so its consistent with the main script file in Framework. This resolves your inquiry where confusion could be introduced due to inconsistent naming conventions of the main script file in each repo.

**Comment by toddmilliken** [comment]
Yup. Pending this PR, I will go through Framework and Child Starter to replicate the same setup. I'm thinking Im going to add a babel preset for `wp.element`/react stuff so that themes are ready to add their own blocks for gutenberg if needed. That would really be the only big change.

I have some next steps for Foundation after this PR as well -- we can begin deprecating our mixins like `@include transform()`, etc in favor of adding autoprefixer. Autoprefixer is a Post CSS plugin that adds vendor prefixes based on a configuration we setup. This is where the `browserslist` key in package.json also comes into play, so we have one defined place of browser support where we can be as specific as we want, and then babel will give us the es6 polyfills we need, and autoprefixer will give us the CSS vendor prefixes we need.

I'm also going to look into adding an `.eslintrc` file for Code Climate so it will stop throwing false/positives for es6 syntax it doesn't recognize.

**Comment by stonybrookweb** [comment]
@toddmilliken  Overall this sounds like a great idea! I definitely like the writing in ES6 and compiling down to ES5.

My biggest concern here from a surface review of this update, does it readily address the question in https://github.com/bu-ist/responsive-framework/issues/74 ?

I was looking for the documentation about how we compile JavaScript in the original issue, I know it's out there somewhere but was unable to find it this morning. It clearly stated how this process worked and warned of the pitfall in the originating issue. Yes, I have fell into the issue myself before and gotten frustrated.

I will download and try this out, but I'd recommend asking some front end designers or producers to try this out to see if it clarifies the process for them. I'd also like to see some documentation for basic usage to go along with this change.

Does this setup match the existing setup for being able to easily not concatenate a JS file into a master file, leaving it separate for conditional loading( especially for use in WordPress)?

Some older reference documentation, but not exactly what I was looking for:
https://github.com/bu-ist/responsive-framework/wiki/Grunt-Tasks#watch
https://github.com/bu-ist/responsive-framework/wiki/Grunt-Tasks#watch
Found it!
https://github.com/bu-ist/responsive-framework-1x/wiki/Customize-Javascript#im-saving-and-my-work-keeps-disappearing-d

**Comment by toddmilliken** [comment]
There are loads of new Code Climate sass-lint errors due to the `.sasslintrc` file being uploaded, and us switching from Code Climate's scss-lint plugin to the sass-lint plugin (needed because scss-lint is for ruby sass and we will be using node-sass).

Most of these errors are of the same nature (uppercase hex codes, mixed tabs/spaces, extra tabs when there should have been less tabs, use of !important, etc).

These rules can be fixed in a later PR or disabled as needed by adding lines like 
```
p {
  border: none; // sass-lint:disable-line border-zero
}

// or for large blocks:

// sass-lint:disable border-zero
p {
  border: none; // No result reported
}
// sass-lint:enable border-zero
```

See https://github.com/sasstools/sass-lint#disabling-linters-via-source for more information on how to ignore the rules with inline comments, or customize your rules in the `.sasslintrc` by browsing thru the rulesets https://github.com/sasstools/sass-lint/tree/develop/lib/rules

**Pull request merged**
